name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: eu-west-1.qa.api.neuphonic.com
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: Install Deps & Run Tests
        run: yarn install --frozen-lockfile && yarn test:ci
